### ISSUE TITLE
Not working on v1.7.7.1 

### ISSUE THREAD

**Issue by lucmichalski** [binshops/prestashop-rest#1]
Hi,

Hope you are all well !

I tried to install your great module on a fresh install of Prestashop V1.7.7.1 and it could not load the plugin.

Any thoughts on how to sort it out ? or maybe why there is an incompatibility .

Thanks for any insights or inputs on that :-)

Cheers,
Luc Michalski

**Comment by vhessam** [comment]
Hi dear Luc,
thanks for reaching out. We have a running REST module on Prestashop version 1.7.7.1 here: 
https://ps.binshops.com/rest/bootstrap

You can also check the document for REST module:
https://www.binshops.com/prestashop-rest-module

Please let us know the error message if the problem persists. 

Warm Regards,
Sam

**Comment by lucmichalski** [comment]
Hi,

It does not say much apart that the following message:

<img width="666" alt="Screenshot 2021-01-31 at 10 17 45" src="https://user-images.githubusercontent.com/1963546/106379647-a8f43200-63ad-11eb-83c3-3c671e7ff557.png">


Cheers,
Luc Michalski

**Comment by vhessam** [comment]
dear Luc,
have you downloaded the module from this link:
https://www.binshops.com/prestashop-rest-module

Regards,
Sam

**Comment by lucmichalski** [comment]
Just got it working, awesome.:-)

Thanks

**Comment by vhessam** [comment]
Very good my friend. 
Welcome.
