### ISSUE TITLE
CORS Issue

### ISSUE THREAD

**Issue by ThibaudSE** [binshops/prestashop-rest#10]
Hello, I've been able to install the module and to make it work with postman but when I'm trying to make it work on my website I got CORS issues: `CORS Preflight Did Not Succeed`.
I was using the classic Prestashop Webservice before trying your module and it was working fine.
Do you have any suggestion to make it work ?

FYI, my frontend is in Reactjs and not on the same domain as Prestashop backend. 
I tried on both localhost and on the production server.

Thank you.

**Comment by samberrry** [comment]
Hi,
change your server configs.
thanks
