### ISSUE TITLE
500 error on productSearch

### ISSUE THREAD

**Issue by david8z** [binshops/prestashop-rest#13]
I'm getting `500 errors` on productSearch is this an expected behaviour?

**Comment by david8z** [comment]
Actually just realize it also returns erro with `rest/bootstrap` path so with a little bit of debugging found out is not currently working with cache disabled :+1:

**Comment by david8z** [comment]
After debugging a bit I found out it is failing at this point any idea how I could debug more or why it could be happening? https://github.com/binshops/prestashop-rest/blob/0b10acf6bdab64d682ea1116f45fc58ba33745ea/classes/RESTProductLazyArray.php#L152-L155

**Comment by samberrry** [comment]
thanks for reporting. 
What's your Ps version?

**Comment by david8z** [comment]
Thanks for the response current PS version `1.7.6.2` and PHP version `7.2.34`

**Comment by samberrry** [comment]
Thank you too. That's why you got error, the module support Ps1.7.7.x and higher version, the older version are not supported. But there is a branch 1.7.6.x, but is not maintained. 
Thanks you David.
