### ISSUE TITLE
Required Modules To Work

### ISSUE THREAD

**Issue by david8z** [binshops/prestashop-rest#14]
The module requires a list of modules in order to work without errors such as:

- [X] productcomments
- [X] ps_mainmenu
- [X] ps_banner
- [X] ps_imageslider

Not sure if more.

It will be nice if they would be listed on the readme. What do you think?

**Comment by samberrry** [comment]
Hi @david8z, 
thanks for your consideration, yes these are all native/default Ps modules, most of them are related to the Bootstrap endpoint for home page data. All the other APIs are independent of these modules, and I think the bootstrap endpoint is somehow project specific.
But it's a good idea to have a list in readme to show that the module works with these modules.

I will add it. Thanks
