### ISSUE TITLE
Strange Response Codes

### ISSUE THREAD

**Issue by david8z** [binshops/prestashop-rest#15]
Have been reading the code and realized response codes are kind of rare many times, returning **Redirection 3xx** error codes when they are actually **Client Error 4xx** or **Server Error 5xx**. 

¿May I create a PR with some changes proposals?

**Comment by samberrry** [comment]
I think it would be better to keep the error codes, also you may testing on old Ps versions.. 
anyway let us discuss it with you internally in channel. 
Thanks David.
