### ISSUE TITLE
 bootstrap.php

### ISSUE THREAD

**Issue by langziyang** [binshops/prestashop-rest#18]
line 66

change
` $id_shop = (int) $this->shop->id;`

to
` $id_shop = (int) $this->context->shop->id;`

**Comment by samberrry** [comment]
what's you ps version?

**Comment by langziyang** [comment]
> what's you ps version?

ps version is 1.8.8.2

but i think each version "shop","customer","cart","language" must use $this->context->   to get it, right?

**Comment by samberrry** [comment]
will be changed. Thanks
