### ISSUE TITLE
JWT token / Swagger panel

### ISSUE THREAD

**Issue by lucmichalski** [binshops/prestashop-rest#2]
Hi again :-)

Hope you are all well !

Is it possible to add a JWT token/bearer to the rest api and swagger panel ?
That would be just awesome :-)

In fact, I d like to create a theme using your rest api like this guy created it with the webservice.
https://github.com/lucmichalski/reactive-prestashop

What are your thoughts about that ?

Thanks for any insights or inputs on this point.

Cheers,
Luc Michalski

**Comment by vhessam** [comment]
Hi dear Luc,

I hope you are doing well too.

We will add the swagger panel in the future (not now really), but for JWT we do not have any plan for it.

If you need customization please email us at: contact@binshops.com

Thanks for your consideration. 

Best Regards,
Sam
