### ISSUE TITLE
Create an order

### ISSUE THREAD

**Issue by amirping** [binshops/prestashop-rest#20]
Hello guys. 
I'm really happy to find your project, in our case it saves us handed of hours and money. 
i have a quick question, I cannot find any doc about adding a new order. is it possible or yet not implemented? 
Thanks

**Comment by samberrry** [comment]
@amirping Hi,
I'm happy to see that it helped you ;)
Can I have your email?

**Comment by amirping** [comment]
Sure.
email : amirs-m-s@live.com
