### ISSUE TITLE
Attempted to call an undefined method named "ajaxRender" of class "BinshopsrestHelloModuleFrontController"

### ISSUE THREAD

**Issue by mspinnler** [binshops/prestashop-rest#25]
On a Prestashop 1.7.4.0 i have this error when i call /rest url with Postman or in browser

**Comment by mspinnler** [comment]
Fixed with adding the function in controller class

`/**
     * @param string|null $value
     * @param string|null $controller
     * @param string|null $method
     *
     * @throws PrestaShopException
     */
    protected function ajaxRender($value = null, $controller = null, $method = null)
    {
        if ($controller === null) {
            $controller = get_class($this);
        }

        if ($method === null) {
            $bt = debug_backtrace(DEBUG_BACKTRACE_IGNORE_ARGS);
            $method = $bt[1]['function'];
        }

        /* @deprecated deprecated since 1.6.1.1 */
        Hook::exec('actionAjaxDieBefore', ['controller' => $controller, 'method' => $method, 'value' => $value]);

        /*
         * @deprecated deprecated since 1.6.1.1
         * use 'actionAjaxDie'.$controller.$method.'Before' instead
         */
        Hook::exec('actionBeforeAjaxDie' . $controller . $method, ['value' => $value]);
        Hook::exec('actionAjaxDie' . $controller . $method . 'Before', ['value' => $value]);
        header('Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0');

        echo $value;
    }`

**Comment by samberrry** [comment]
@mspinnler thanks for reporting. This module works with Ps 1.7.7.x and higher, and lower versions are not supported. You may face other issues with other endpoints, I recommend to upgrade your Ps.
Thanks
