### ISSUE TITLE
How to pass an order after checkout

### ISSUE THREAD

**Issue by amirping** [binshops/prestashop-rest#29]
Hello there

we are using the pro version, and it is going well so far,
but we can't find to validate a cart into order after setting a carrier & address.

**Comment by samberrry** [comment]
> Hello there
> 
> we are using the pro version, and it is going well so far, but we can't find to validate a cart into order after setting a carrier & address.

Hello,
thank you. 
Yes we do not have any a separate API for validateOrder, because it should happen within payment APIs and payment modules. However, if you just want to call API to place order, you can use bankwire or paybycheck endpoints.

**Comment by amirping** [comment]
Well let me explain the case, 
the current PrestaShop store doesn't have any online payment solution, all payments are made on delivery.
we followed the documentation  : 
1- create a cart 
2- set address
3- set carrier 
4- how we can submit now?
we see that there is an API under Admin API there is create order API, but I don't believe that's for users.

**Comment by samberrry** [comment]
> Well let me explain the case, the current PrestaShop store doesn't have any online payment solution, all payments are made on delivery. we followed the documentation : 1- create a cart 2- set address 3- set carrier 4- how we can submit now? we see that there is an API under Admin API there is create order API, but I don't believe that's for users.

No you should not use the Admin API, that's for accepting orders from outside of the system, you are correct it's not for users. As I said it should be done through a payment module, you can simply have an API to to just call validateOrder method, or we can simply add support for COD module, so you can do your payments through COD module.

**Comment by amirping** [comment]
It will be awesome if we have COD support, in meantime, I will try to create some API to call validateOrder.

**Comment by samberrry** [comment]
> It will be awesome if we have COD support, in meantime, I will try to create some API to call validateOrder.

I added COD support to v2.4.4 version. You can check it.

**Comment by amirping** [comment]
Thanks buddy 😚 
 is it included in the pro version?

**Comment by samberrry** [comment]
> Thanks buddy 😚 is it included in the pro version?

welcome ;) We will add it soon.

**Comment by samberrry** [comment]
Pro version is also updated. 
So, I close this issue.
