### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by ttoine** [binshops/prestashop-rest#3]
Hello,
This module is very promising, but in order to foster adoption, having a license file would be very important so people know that they have the right to use it.

In the PrestaShop ecosystem, AFL is recommended for modules. MIT is also a good one. You can see an example in any native module. And, I would enjoy to help you if needed. Let me know, we can also talk together (call, or on the community slack).

Note: please avoid GPL family of license, it's not compatible with OSL and AFL licenses used in PrestaShop core and modules.

**Comment by sam-beri** [comment]
Hello,
many thanks for your consideration dear friend. Sure, we will add the license to the product.

Also, we would be happy to see you on slack as our early adapters. Here is the slack link:
https://binshopsworkspace.slack.com/archives/C01P4EP7DUP

**Comment by sam-beri** [comment]
@ttoine dear Antonie, we have added the license file. 
If you have any other issue, feel free to open the issue again. Thank you

**Comment by ttoine** [comment]
thanks :-)
I know that your module is currently review and at the center of interest of some people in France. Expect them to contact you soon :-)

**Comment by sam-beri** [comment]
It's really a pleasure. We are happy if we are helping the community.
Thank you my friend
