### ISSUE TITLE
Public API Rest response

### ISSUE THREAD

**Issue by msaustral** [binshops/prestashop-rest#30]
Hi is there a way to have and authentication before responding to any api request?

otherwise all store information will be public, anyone with access to the api documentation will be able to retrieve any information

**Comment by samberrry** [comment]
> Hi is there a way to have and authentication before responding to any api request?
> 
> otherwise all store information will be public, anyone with access to the api documentation will be able to retrieve any information

Hi, these are front APIs not admin APIs, and they are supposed to be public for anyone. That's like that everyone can see your home page or your product details like what we have with PrestaShop by default (or any other shop), should people authenticate before accessing our front office? normally we do not expect this. Also, there are some protected APIs like getting order details, or profile info that need users/customers login.
