### ISSUE TITLE
bootstrap response

### ISSUE THREAD

**Issue by jalalannan** [binshops/prestashop-rest#34]
in RESTMainMenu throw an error

line: 145
code: $this->mainmenu_module->trans('All brands', [], 'Modules.Mainmenu.Admin'),

Error: Call to protected method ModuleCore::trans() from context 'RESTMainMenu'

Iam using 1.7.8.6

**Comment by samberrry** [comment]
> in RESTMainMenu throw an error
> 
> line: 145 code: $this->mainmenu_module->trans('All brands', [], 'Modules.Mainmenu.Admin'),
> 
> Error: Call to protected method ModuleCore::trans() from context 'RESTMainMenu'
> 
> Iam using 1.7.8.6

Thanks for your report.

Just updated the repo (v2.4.5).
