### ISSUE TITLE
Language parameters

### ISSUE THREAD

**Issue by jalalannan** [binshops/prestashop-rest#35]
do you support language search products?

if not. can I create branches and added the missing codes?

Since I am creating mobile app from scratch according to APIs
Thank you

**Comment by samberrry** [comment]
> do you support language search products?
> 
> if not. can I create branches and added the missing codes?
> 
> Since I am creating mobile app from scratch according to APIs Thank you

Hello,
thanks for your interest. 

- would you please explain a bit about language search products?
- this module is aimed at exposing APIs for PrestaShop core logic (and native modules), so you may have many other custom logics within your app, but it does not fall into the scope of this module. However, if you see there is a missing Core functionality that is not present in the API, do not hesitate to make PR, it's welcomed.
thanks

**Comment by jalalannan** [comment]
When I make request to get product details

Always received in english language so I update the code of all apis to be compatible with language.

Is Your pro version can use it for many websites?

**Comment by samberrry** [comment]
> When I make request to get product details
> 
> Always received in english language so I update the code of all apis to be compatible with language.
> 
> Is Your pro version can use it for many websites?

Got it. Multi lang is already supported on all endpoints.
For example, you can get list of all languages from this endpoint: 
https://rest.binshops.com/rest/bootstrap

then, you can call each language for all endpoints this way:
https://rest.binshops.com/it/rest/bootstrap
(seems that the products and strings are not translated on this shop, but the logic works well)

There are much more tricks that you can read from the doc that is included in pro version. 

It would be better to purchase for each website, to help us to support this module as much as possible.
