### ISSUE TITLE
Problème Register Endpoint 

### ISSUE THREAD

**Issue by foybkaa** [binshops/prestashop-rest#4]
Bonjour, 

Après avoir installé le module Binshops REST, j'ai testé sur Postman les différentes routes dont j'allais avoir besoin pour construire un front entièrement en React. 

J'aimerais pouvoir inscrire un nouveau Customer, j'ai donc suivi la documentation : [Doc postman](https://documenter.getpostman.com/view/1491681/SWT5jMRb#d124ef45-00d7-428c-aa7a-e3821308dd7c)

 J'ai dans un premier temps reçu une erreur : 307 "gender required", j'ai donc rajouté  un gender, premier problème résolu facilement grâce au message d'erreur, merci.
 
 Par contre une fois tous mes paramètres renseignés et valide je reçois un status 200 avec en message d'erreur :    
```
{
 "success": false,
  "code": 300,
  "psdata": "Internal Server Error"
  }
```
  
Après avoir regardé le dans le fichier Register.php la méthode processPostRequest de plus près, j'ai remarqué grâce à differents var_dump() que qu'il passait en catch au moment du save : `$status = $cp->save($customer, $password);` mais je n'arrive pas à comprendre pourquoi ?
  
Si quelqu'un à déjà été confronté à ce problème, ou si quelqu'un à une idée pour le résoudre, merci d'avance.
 
![image](https://user-images.githubusercontent.com/39589466/113311152-47970380-9309-11eb-9372-3e7c70716854.png)

**Comment by sam-beri** [comment]
Bonjour @foybkaa , merci d'avoir contacté,
quelle version de Prestashop utilisez-vous?

**Comment by foybkaa** [comment]
Ma version de Prestashop est la :  1.7.7.2

**Comment by sam-beri** [comment]
@foybkaa 
Merci. il y a peut-être un problème d'incompatibilité. Nous allons le réparer bientôt.

**Comment by sam-beri** [comment]
@foybkaa 
veuillez vérifier le facteur, nous l'avons mis à jour. Et nous avons également mis à jour le code afin qu'il renvoie maintenant la raison de l'erreur. Faites-moi savoir si vous avez un problème.

**Comment by foybkaa** [comment]
Merci !  ça fonctionne
Grâce à la mise à jour j'ai  eu le message d'erreur suivant 
`{
    "success": false,
    "code": 300,
    "psdata": "Property Customer->lastname is not valid"
}`

En effet dans mon champ lastName j'avais mis : test2 
J'ai enlevé le chiffre et la requête fonctionne au top ! mon Customer s'enregistre bien en BDD

**Comment by sam-beri** [comment]
très bien, heureux d'entendre ça.
Bonne journée.

**Comment by foybkaa** [comment]
Merci depuis la France !
Chez nous c'est l'heure de se coucher 22:20 :)

**Comment by sam-beri** [comment]
Oh, nous sommes au Canada.
Alors, passez une bonne nuit.
