### ISSUE TITLE
Payment options do not work with payU module

### ISSUE THREAD

**Issue by roszpun** [binshops/prestashop-rest#49]
Hey, so I try to implement additional payment method - PayU -  https://github.com/PayU-EMEA/plugin_prestashop. Once I enable it I receive 500 error on the VSF implementation. 

`Cannot read properties of undefined (reading 'code')` 
```js

      const { data } = await $vsf.$prestashop.api.getPaymentMethods({ psCookieKey, psCookieValue });
      if (data.code === 200) {
        if (Object.keys(data.psdata).length === 0) {
          app.context.redirect('/checkout/shipping');
        }
      } else {
        app.context.redirect('/checkout/shipping');
```
in `middleware/checkout.js`

Any ideas what can cause this issue? I tried other Polish based provider and it worked without issues.

**Comment by samberrry** [comment]
Hey,
VSF 2 is deprecated, so we stopped active development on it, but it's a good sample to get familiar with headless/modern front idea. FYI,currently we are working on something new based on React.js, 

have a super day.
