### ISSUE TITLE
Postman problem with endponit

### ISSUE THREAD

**Issue by cianopman** [binshops/prestashop-rest#7]
Hi, I'm testing your module with postman and I be able to make a succesfully login, I get back the PrestaShop cookie but when I try an other endponit (ie AccountInfo) I get the error "User not authenticated". I checked the request header and the cookie is sent with other data.
I also tried to make the same on a php page using php cURL code generated by postman but the login endpoint give me the error "An email address required".
Using Postman 8.6.2 and Prestashop 1.7.7

Thank you

**Comment by samberrry** [comment]
Hi @cianopman , thanks for reporting.
We will check it.

**Comment by samberrry** [comment]
https://user-images.githubusercontent.com/20775532/122570145-188f5480-d011-11eb-8631-e98a5f705be9.mov

As I've checked the authentication works well. Please check the way you are setting session cookies.

**Comment by cianopman** [comment]
Hi @samberrry, I have checked the cookies postman usage, and I don't think there is some problem about that, as you can see by the attached images the login response set the cookies that postman uses to make the accountinfo request. I also saw that in the admin cart panel the new empty cart was created for the related user but the ps_customer_session table still empty.
Login request
![immagine](https://user-images.githubusercontent.com/85196476/123096941-e9714c80-d42f-11eb-8eb3-6da983ae7c26.png)
Accountinfo request
![immagine](https://user-images.githubusercontent.com/85196476/123097039-0443c100-d430-11eb-8cec-a0def41227a2.png)

Thank you
