### ISSUE TITLE
about facets

### ISSUE THREAD

**Issue by OguzhanLevent** [binshops/prestashop-rest#8]
I'm trying to filter on a category, but failed.

`   
        if ($provider instanceof FacetsRendererInterface) {
            // with the provider if it wants to
            $rendered_facets = $provider->renderFacets(
                $context,
                $result
            );
            $rendered_active_filters = $provider->renderActiveFilters(
                $context,
                $result
            );
        } else {
            // with the core
            $rendered_facets = $this->renderFacets(
                $result
            );
            $rendered_active_filters = $this->renderActiveFilters(
                $result
            );
        }
`

How can I find and use filter variables?

**Comment by samberrry** [comment]
Hi @OguzhanLevent ,
the faceted module and search functionality is not available in this version. The pro version has complete access to search and facets.

**Comment by OguzhanLevent** [comment]
Hello, I have been developing the module myself since about June. As an extra, I added many features to the module, including payment.

I also want to contribute to this module for free, but it is a bit cruel for you to finish the module and put it up for sale.

for example; https://prnt.sc/1qgvr0v

have a nice day.

**Comment by samberrry** [comment]
Hi @OguzhanLevent,
that's nice. Would you please leave your email here to discuss it more?

Thanks

**Comment by OguzhanLevent** [comment]
byhero41@gmail.com

you can contact me
