### ISSUE TITLE
Do not include mixed license headers

### ISSUE THREAD

**Issue by matks** [binshops/prestashop-rest#9]
Hello, I can find some files that have a AFL license header from PrestaShop:

Examples
- https://github.com/binshops/prestashop-rest/blob/master/index.php
- https://github.com/binshops/prestashop-rest/blob/master/controllers/index.php

I think you should have a common unified license header for all PHP files.

**Comment by samberrry** [comment]
@matks thanks you.
yes you are right. I will change the license to AFL so that everyone can use, share and distribute it.
As the module was on ps addon I added the BINSHOPS license.

**Comment by samberrry** [comment]
@matks again thanks. 
License updated.
